[tool.poetry]
name = "samarium"
version = "0.3.1"
description = "The Samarium Programming Language"
authors = ["trag1c <trag1cdev@yahoo.com>"]
license = "MIT"
documentation = "https://samarium-lang.github.io/Samarium/"
repository = "https://github.com/samarium-lang/Samarium"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
dahlia = "^2.0.0"
curtsies = "^0.4.0"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"

[tool.poetry.scripts]
samarium = "samarium.__main__:main"
samarium-debug = "samarium.__main__:main_debug"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

